<?php
if (empty($this->repositories)) {
?>
<div class="alert alert-block">No modules found</div>
<?php
}

foreach($repositories as $module) {
    echo $this->moduleView(array(
        'owner' => $module->owner->login,
        'name' => $module->name,
        'created_at' => $module->created_at,
        'url' => $module->html_url,
        'photo_url' => $module->owner->avatar_url,
        'description' => $module->description
        ), 'submit');
}
?>