<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <link href="/style/font.css" rel="stylesheet" media="screen, projection" type="text/css" />
        <link href="/style/setup.css" rel="stylesheet" media="screen, projection" type="text/css" />
        <link href="/style/default.css" rel="stylesheet" media="screen, projection" type="text/css" />
        <script src="/script/lib/modernizr-2.0.6.js"></script>
    </head>
    <body>
        <header class="clearfix">
            <figure>
                <img src="/image/logo.png" alt="Zend Framework Modules"/>
                <figcaption>MODULES</figcaption>
            </figure>
            <form>
                <input type="search" autocomplete="on" required placeholder="Search Coming Soon" /><button>Search</button>
            </form>
            <nav>
                <ul>
                    <li class="active"><a href="#welcome" title="Welcome">Welcome</a></li>
                    <li><a href="#help" title="We Need Help"">We Need Help</a></li>
                    <li><a href="#modules" title="Modules">Modules</a></li>
                </ul>
            </nav>
        </header>
        <div id="content" class="clearfix">
            <?php echo $this->raw('content'); ?>
        </div>
        <aside class="clearfix">
            <a href="http://www.redmeatcreative.co.uk/" title="Redmeat Creative">
                <figure>
                    <figcaption>Design Generously contributed by</figcaption>
                    <img alt="Redmeat" src="http://www.redmeatcreative.co.uk/css/images/logo.png" />
                </figure>
            </a>
        </aside>
        <footer class="clearfix">
            &copy; <?= date('Y'); ?> by Zend Technologies Ltd. All rights reserved.
        </footer>
        <aside class="corner">
            <a href="https://github.com/zendframework/modules.zendframework.com" title="Fork me on Github">
                <img src="https://a248.e.akamai.net/assets.github.com/img/71eeaab9d563c2b3c590319b398dd35683265e85/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub">
            </a>
        </aside>
    </body>
</html>
