<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <link href="/css/default.css" rel="stylesheet" media="screen, projection" type="text/css" />
    </head>
    <body>
        <div id="header">
            
            <div id="primary">
                <div class="content clearfix">
                    <h1>
                        <img src="/images/zf2-logo-white-small.png" alt="ZF2" title="ZF2" />
                        <span id="local-site-name">
                            Modules
                        </span>
                    </h1>
                </div>
            </div>
            
            <div id="secondary">
                <div class="content clearfix">
                    <a href="#welcome">Welcome</a> |
                    <a href="#help">We Need Help!</a> |
                    <a href="#links">Modules</a>
                </div>
            </div>
            
        </div>

        <div id="content-area">
            <div class="content clearfix">

<?php echo $this->raw('content'); ?>

            </div>

        </div>

        <div id="footer">
            &copy; <?= date('Y'); ?>
        </div>
        <a href="https://github.com/zendframework/modules.zendframework.com"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://a248.e.akamai.net/assets.github.com/img/e6bef7a091f5f3138b8cd40bc3e114258dd68ddf/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub"></a>
    </body>
</html>
