<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <link href="/style/font.css" rel="stylesheet" media="screen, projection" type="text/css" />
        <link href="/style/setup.css" rel="stylesheet" media="screen, projection" type="text/css" />
        <link href="/style/default.css" rel="stylesheet" media="screen, projection" type="text/css" />
        <script src="/script/lib/modernizr-2.0.6.js"></script>
    </head>
    <body>
        <header class="clearfix">
            <figure>
                <img src="/image/logo.png" alt="Zend Framework Modules"/>
                <figcaption>MODULES</figcaption>
            </figure>
            <form>
                <input type="search" autocomplete="on" required placeholder="Search Coming Soon" /><button>Search</button>
            </form>
            <nav>
                <ul>
                    <li class="active"><a href="#welcome">Welcome</a></li>
                    <li><a href="#help">We Need Help</a></li>
                    <li><a href="#modules">Modules</a></li>
                </ul>
            </nav>
        </header>
        <div id="content" class="clearfix">
            <?php echo $this->raw('content'); ?>
        </div>
        <aside class="clearfix">
            <a href="http://www.redmeatcreative.co.uk/" title="Redmeat Creative">
                <figure>
                    <figcaption>Design Generously contributed by</figcaption>
                    <img alt="Redmeat" src="http://www.redmeatcreative.co.uk/css/images/logo.png" width="145" height="50" />
                </figure>
            </a>
        </aside>
        <footer class="clearfix">
            &copy; <?= date('Y'); ?> by Zend Technologies Ltd. All rights reserved.
        </footer>
        <aside class="corner">
            <a href="" title="Fork me on GitHub">
                <img src="/image/github.png" alt="Fork me on GitHub" />
            </a>
        </aside>
    </body>
</html>
