<h1>Welcome to the ZF2 Modules Site</h1>

<article class="triple">
    <header>We need help - Be a volunteer</header>
    <div>
        <p>Vivamus sit amet metus non mi euismod iaculis. Proin leo libero, suscipit non consectetur quis, aliquet non dui. Ut erat neque</p>
        <p>Phasellus nisl risus, vulputate eu dictum sodales, gravida ut enim. Integer nisl lectus, fermentum vitae consectetur vitae, commodo sed justo. </p>
        <p>Donec bibendum erat nec lorem tincidunt eu sagittis velit faucibus. Sed ornare ornare ultricies. Proin nisl dolor, ullamcorper a adipiscing in</p>
        <p><strong>Fusce cursus luctus nibh, vitae egestas libero imperdiet ac. Mauris fermentum consequat porttitor. Pellentesque condimentum libero nisl. Proin bibendum, purus vulputate tincidunt </strong></p>
        <p><a href="#">Phasellus nisl risus</a></p>
    </div>
</article>


<article class="triple last">
    <header>Modules</header>
    <div>
        <p>Vivamus sit amet metus non mi euismod iaculis. Proin leo libero, suscipit non consectetur quis, aliquet non dui. Ut erat neque</p>
        <p>Phasellus nisl risus, vulputate eu dictum sodales, gravida ut enim. Integer nisl lectus, fermentum vitae consectetur vitae, commodo sed justo. </p>
        <p>Donec bibendum erat nec lorem tincidunt eu sagittis velit faucibus. Sed ornare ornare ultricies. Proin nisl dolor, ullamcorper a adipiscing in</p>
        <p><strong>Fusce cursus luctus nibh, vitae egestas libero imperdiet ac. Mauris fermentum consequat porttitor. Pellentesque condimentum libero nisl. Proin bibendum, purus vulputate tincidunt </strong></p>
        <p><a href="#">Phasellus nisl risus</a></p>
    </div>
</article>


<!-- 
<a name="welcome"></a>
<h2>Welcome to the ZF2 modules site</h2>
<p>The goal of this site is to provide a central location for browsing, searching, reviewing ZF2 modules.</p>
            
<a name="help"></a>
<h2>We Need Help!</h2>
<p>We are actively recruiting volunteers to help build this community site. If you are interested in helping with this project, please make sure you have signed the <a href="http://framework.zend.com/wiki/display/ZFPROP/Contributor+License+Agreement">Zend Framework CLA</a> and <a href="https://github.com/zendframework/modules.zendframework.com">fork the code on GitHub</a>. Additionally, join us in #zftalk.2 on Freenode and ask how you can help!</p>

<a name="links"></a>
<h2>Modules</h2>
<p>The new ZF2 module system is very young; and as such, there are not many modules yet. Below are some links to modules under development. Remember, ZF2 and the module system is <strong>beta</strong> and not meant to be used in production.</p>

<ul>
    <li><strong><a href="https://github.com/zendframework/ZendSkeletonModule">ZendSkeletonModule</a></strong> - Provides a simple starting place for developing typical MVC-oriented modules.</li>
    <li><strong><a href="https://github.com/zendframework/ZendDeveloperTools">ZendDeveloperTools</a></strong> - Will eventually provide a JS/CSS floating toolbar with helpful debugging tools such as profiling and debugging output.</li>
    <li><strong><a href="https://github.com/SpiffyJr/SpiffyDoctrine">SpiffyDoctrine</a></strong> - Provides simple integration of Doctrine 2.x for your ZF2 application. By <a href="http://www.spiffyjr.me/">Kyle Spraggs</a>.</li>
    <li><strong><a href="https://github.com/EvanDotPro/zf2-user-module">User Module</a></strong> - Provides a very simple authentication and registration system. By <a href="http://blog.evan.pro/">Evan Coury</a>.</li>
    <li><strong><a href="https://github.com/EvanDotPro/EdpMarkdown">EdpMarkdown</a></strong> - Uses the <a href="http://michelf.com/projects/php-markdown/">PHP Markdown</a> parser to provide a very simple markdown view helper. By <a href="http://blog.evan.pro/">Evan Coury</a>.</li>
    <li><strong><a href="https://github.com/DASPRiD/Bacon">Bacon</a></strong> - Provides a unidecoder/slugifier, as well a as a PHP port of 'highlight'. By <a href="http://www.dasprids.de/">Ben Scholzen</a>.</li>
    <li><strong><a href="https://github.com/EvanDotPro/zf2-guestbook-module">Guestbook Module</a></strong> - Provides very simple Guestbook functionality. By <a href="http://weierophinney.net/matthew/">Matthew Weier O'Phinney</a>.</li>
</ul>

<p>If you would like to have your module added to this list, let us know in #zftalk.2 on Freenode.</p>
-->