<?php $this->layout()->single = true; ?>

<?php if (isset($this->reason) && $this->reason): ?>

<?php
$reasonMessage= '';
switch ($this->reason) {
    case 'error-controller-cannot-dispatch':
        $reasonMessage = 'The requested controller was unable to dispatch the request.';
        break;
    case 'error-controller-not-found':
        $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
        break;
    case 'error-controller-invalid':
        $reasonMessage = 'The requested controller was not dispatchable.';
        break;
    case 'error-router-no-match':
        $reasonMessage = 'The requested URL could not be matched by routing.';
        break;
    default:
        $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
        break;
}
$errorText = array(
    "NO, Zend Framework is <strong>not</strong> to blame for this!",
    $reasonMessage,
);
?>

<div class="error-404">
    <div class="error-404-speech-bubble">
        <h1>A 404 error occurred</h1>

        <h2><?php echo $this->message ?></h2>

        <p><?php echo $errorText[array_rand($errorText)]; ?></p>
    </div>
</div>


<?php endif ?>

<?php if (isset($this->controller) && $this->controller): ?>

<dl>
    <dt>Controller:</dt>
    <dd><?php echo $this->escapeHtml($this->controller) ?>
<?php
if (isset($this->controller_class)
    && $this->controller_class
    && $this->controller_class != $this->controller
) {
    echo '(' . sprintf('resolves to %s', $this->escapeHtml($this->controller_class)) . ')';
}
?>
</dd>
</dl>

<?php endif ?>

<?php if (isset($this->exception) && $this->exception): ?>

<h2>Exception:</h2>

<p><b><?php echo $this->escapeHtml($this->exception->getMessage()) ?></b></p>

<h3>Stack trace:</h3>

<pre>
<?php echo $this->exception->getTraceAsString() ?>
</pre>

<?php endif ?>