<?php $this->headTitle('List of awesome contributors'); ?>

<h1>Contributors Hall of Fame</h1>

<div class="row">
    <div class="col-lg-12">
        <p>
            We have <strong><?php echo $this->escapeHtml($this->metadata->forks_count); ?> forks</strong>,
            <strong><?php echo $this->escapeHtml($this->metadata->stargazers_count); ?> stargazers</strong>,
            <strong><?php echo $this->escapeHtml($this->metadata->watchers_count); ?> watchers</strong> and
            <strong><?php echo count($this->contributors); ?> awesome contributors</strong> who make this site better.
            <a href="<?php echo $this->escapeHtmlAttr($this->gitHubRepositoryUrl()); ?>" target="_blank">Join us!</a>
        </p>
    </div>
    <?php foreach ($this->contributors as $contributor): ?>
    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-3">
        <?php $url = $contributor->author->html_url; ?>
        <a href="<?php echo $this->escapeHtmlAttr($url); ?>" class="thumbnail img-responsive" target="_blank">
            <?php $src = $contributor->author->avatar_url; ?>
            <?php $alt = $contributor->author->login; ?>
            <?php $title = sprintf('%s with %d contributions', $alt, $contributor->total); ?>
            <img src="<?php echo $this->escapeHtmlAttr($src); ?>" alt="<?php echo $this->escapeHtmlAttr($alt); ?>" title="<?php echo $this->escapeHtmlAttr($title); ?>">
        </a>
    </div>
    <?php endforeach; ?>
</div>
