<?php $this->headTitle('List of awesome contributors'); ?>

<h1>Contributors Hall of Fame</h1>

<div class="row">
    <div class="col-md-12">
        <p>
            We have <strong><?php echo $this->escapeHtml($this->metadata->forks_count); ?> forks</strong>,
            <strong><?php echo $this->escapeHtml($this->metadata->stargazers_count); ?> stargazers</strong>,
            <strong><?php echo $this->escapeHtml($this->metadata->watchers_count); ?> watchers</strong> and
            <strong>awesome contributors</strong> who make a better this site.
            <a href="<?php echo $this->escapeHtmlAttr($this->githubRepositoryUrl()); ?>">Join us!</a>
        </p>
        <?php foreach ($this->contributors as $contributor): ?>
            <a href="<?php echo $this->escapeHtmlAttr($contributor['author']['html_url']); ?>" class="thumbnail col-md-1">
                <img src="<?php echo $this->escapeHtmlAttr($contributor['author']['avatar_url']); ?>" alt="<?php echo $this->escapeHtmlAttr($contributor['author']['login']); ?>" title="<?php echo $this->escapeHtmlAttr(sprintf('%s with %d contributions', $contributor['author']['login'], $contributor['total'])) ?>" width="80px" height="80px">
            </a>
        <?php endforeach; ?>
    </div>
</div>
