


<div class="container-fluid landing-intro">
  <div class="container">
    <div class="row">
      <div class="span8">
        <h1 class="zf-green">
          Welcome to the ZF2 Modules Site
          <br />
          <small>
            Some awesome sentence about modules
          </small>
        </h1>
        <p>
         This website is a work-in-progress. In the future you will be able to use this website to browse, search, rate, and comment on all of the great modules the Zend Framework community has to offer.
          <hr />
        <blockquote>
          <p>
            <em>
              Hell, we might even throw in something cheesy like a hipster quote.
            </em>
          </p>
          <small>
            Someone idiot
            <cite title="Source Title">
              Hipster
            </cite>
          </small>
        </blockquote>
      </p>
    </div>
    <div class="span4">

      <img class="attentionimage pull-right" src="img/rsz_logo.png" />
    </div>
  </div>
</div>
</div>



<div class="container main-content">
  <div class="row">
    <div class="span8">
      <div class="row-fluid">
        <div class="span12">
          <div class="navbar">
            <div class="navbar-inner">
              <h1 class="zf-green">Avilable Modules</h1>
              <p>Select which module you want to Submit for Listing</p>
            </div>
          </div>
        </div>
      </div>

<?php
    $result = $this->userRepositories();
    foreach($result['repositories'] as $module) {
?>

      <div class="row-fluid module-row">
        <div class="span12">
            <div class="row-fluid">
                <div class="module-info">
                    <div class="span5 module-author">
                        <div class="row-fluid">
                            <div class="span2">
                                <?php $owner = $module->getOwner(); ?>
                                <img src="<?=$owner['avatar_url']?> " />
                            </div>
                            <div class="span10">
                                <strong><?=$owner['login']?></strong>
                                <p>
                                    <span class="author-label">Github:</span>
                                    <a href="<?=$module->getUrl()?>"><?=$module->getName()?></a><br />
                                    <!--
                                    <span class="author-label">Blog:</span> <a>placeholder</a><br />
                                    <span class="author-label">Modules:</span> <a>5</a><br /><br />
                                    <span class="author-label"><a>More info...</a>-->
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="span5">
                        <strong><?=$module->getName()?></strong>
                        <p>
                            <!--<span class="author-label">Version:</span> 1.2.1<br />-->
                            <span class="author-label">Created:</span>
                            <?php
                            $date = new DateTime($module->getCreatedAt());
                            echo $date->format('Y-m-d');
                            ?><br />
                            <!--<span class="author-label">Edited:</span> <a>15 days ago</a><br />
                            <span class="author-label">Tags:</span>
                            <span class="label">zf2</span>
                            <span class="label">Assetic</span>
                            <span class="label">Assets</span>
                            <span class="label">Sx</span>-->
                        </p>
                    </div>
                    <div class="span1">
                        <br />
                        <form action="/share-module" method="post">
                            <input type="hidden" name="repository" value="<?=$module->getHtmlUrl()?>" />
                            <input type="submit" />
                        </form>
                    </div>
                    <div style="clear: both;"></div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="module-description">
                    <div class="span12">
                        <strong>Description</strong>
                        <p>
                            <?=$module->getDescription()?>
                        </p>
                    </div>
                    <div style="clear: both;"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>


  </div>
  <div class="span4">
    <div class="sidebar">
      <h3 style="text-align:center">Hello, <?php echo $this->zfcUserDisplayName(); ?>!</h3>
      <img class="thumbnail" src="<?php
          echo $this->zfcUserIdentity()->getPhotoUrl();
      ?>" alt="<?php echo $this->zfcUserDisplayName(); ?>"/>
      <br/>
    </div>
  </div>
</div>