<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <div class="navbar">
                    <div class="navbar-inner">
                        <h1 class="zf-green">Available Modules</h1>
                        <p>Select which module you want to Submit for Listing</p>
                    </div>
                </div>
            </div>
        </div>
        <?php foreach ($this->flashMessenger()->getMessages() as $message): ?>
            <h3 class="zf-green"><?php echo $this->escapeHtml($message); ?></h3>
        <?php endforeach; ?>

        <ul class="nav nav-tabs">
            <li class="active"><a href="#modules" data-toggle="tab">Registered Modules</a></li>
            <li><a href="#repositories" data-toggle="tab">My Modules</a></li>
            <li><a href="#organizations" data-toggle="tab">My Organizations</a></li>
        </ul>
        <br />
        <div class="tab-content">
            <div class="tab-pane active" id="modules">
            <?php /* @var ZfModule\Entity\Module[] $modules */ ?>
            <?php if (!count($modules)): ?>
                <div class="alert alert-block">No modules have been submitted yet</div>
            <?php else: ?>
                <?php foreach ($modules as $module): ?>
                    <?php echo $this->moduleView($module, ZfModule\View\Helper\ModuleView::BUTTON_REMOVE); ?>
                <?php endforeach; ?>
            <?php endif; ?>
            </div>
            <div class="tab-pane" id="repositories">
                <div class="well" style="text-align:center">Synchronizing with GitHub <img src="<?php echo $this->basePath('/img/ajax-loader.gif'); ?>" alt="loading" /></div>
            </div>

            <div class="tab-pane" id="organizations">
                <?php echo $this->userOrganizations(); ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="sidebar" style="text-align: center">
            <h3 style="text-align:center">Hello, <?php echo $this->zfcUserDisplayName(); ?>!</h3>
            <?php /* @var User\Entity\User $identity */ ?>
            <?php $identity = $this->zfcUserIdentity(); ?>
            <img class="thumbnail" src="<?php echo $identity->getPhotoUrl(); ?>" alt="<?php echo $this->zfcUserDisplayName() ?>"/>
            <br/>
        </div>
    </div>
</div>
<?php $this->inlineScript()->appendScript('$("#repositories").load("' . $this->escapeJs($this->url('zf-module')) . '");'); ?>
