<div class="block">
    <div class="row">
        <div class="span4">
            <h4>
                New Developers
            </h4>
            <hr>
        </div>
    </div>

    <?php
    $count = 0;
    foreach($this->users as $user) {
        if($count%4 == 0){
    ?>
    <div class="row-fluid" style="margin-bottom:10px;">
        <div class="span12">
        <?php } ?>
            <div class="span3">
                <a href="https://github.com/<?php echo $user->getUserName()?>" data-delay="0" rel="tooltip" title="<?php echo $user->getUserName()?>" class="thumbnail">
                 <img src="<?php echo $user->getPhotoUrl()?>" alt="<?php echo $user->getUserName()?>">
                </a>
            </div>
    <?php if($count%4 ==3){ ?>
        </div>
    </div>
    <?php
        }
        $count++;
    }
    ?>

</div>