<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                        => __DIR__ . '/Module.php',
    'User\Entity\User'                   => __DIR__ . '/src/User/Entity/User.php',
    'User\Controller\ModuleController'   => __DIR__ . '/src/User/Controller/ModuleController.php',
    'User\View\Helper\Module'            => __DIR__ . '/src/User/View/Helper/Module.php',
    'User\View\Helper\UserRepositories'  => __DIR__ . '/src/User/View/Helper/UserRepositories.php',
    'User\View\Helper\NewUsers'          => __DIR__ . '/src/User/View/Helper/NewUsers.php',
    'User\View\Helper\UserOrganizations' => __DIR__ . '/src/User/View/Helper/UserOrganizations.php',
    'User\Mapper\User'                   => __DIR__ . '/src/User/Mapper/User.php',
    'User\Mapper\UserHydrator'           => __DIR__ . '/src/User/Mapper/UserHydrator.php',
);
