<div class="block">
    <h4><strong>New Modules</strong></h4>
    <hr>
    <?php /* @var ZfModule\Entity\Module[] $modules */ ?>
    <?php foreach ($modules as $module): ?>
        <div class="row">
            <div class="col-md-3">
                <img src="<?php echo $this->escapeHtmlAttr($module->getPhotoUrl()) ?>" alt="<?php echo $this->escapeHtmlAttr($module->getName()) ?>" class="thumbnail img-responsive">
            </div>
            <div class="col-md-9">
                <a href="<?php echo $this->url('view-module', ['vendor' => $this->escapeUrl($module->getOwner()), 'module' => $this->escapeUrl($module->getName())]) ?>">
                    <?php echo $this->escapeHtml($module->getOwner()); ?>/<?php echo $this->escapeHtml($module->getName()); ?>
                </a>
            </div>
        </div>
        <hr>
    <?php endforeach; ?>
</div>
