<div class="block">
    <div class="row">
        <div class="span4">
            <h4>
                New Modules
            </h4>
            <hr>
        </div>
    </div>
    <?php
      foreach($modules as $module) {
    ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="span2">
                <img src="<?php echo $module->getPhotoUrl()?>" alt="<?php echo $module->getName()?>">
            </div>
            <div class="span10">
                <a href="<?php echo $this->url('view-module', array(
                                                    'vendor' => $module->getOwner(),
                                                    'module' =>  $module->getName(),
                                                )
                                            );?>"><?php echo $module->getName()?></a><br>
                <strong>Author:</strong> <?php echo $module->getOwner()?>
            </div>
        </div>
    </div>
    <hr>
    <?php } ?>
</div>

