<div class="block">
    <div class="row">
        <div class="span4">
            <h4>New Modules</h4>
            <hr>
        </div>
    </div>
    <?php foreach ($modules as $module): ?>
        <div class="row-fluid">
            <div class="span3">
                <img src="<?php echo $this->escapeHtmlAttr($module->getPhotoUrl()) ?>" alt="<?php echo $this->escapeHtmlAttr($module->getName()) ?>" class="avatar">
            </div>
            <div class="span9">
                <a href="<?php echo $this->url('view-module', array('vendor' => $this->escapeUrl($module->getOwner()), 'module' => $this->escapeUrl($module->getName()))) ?>">
                    <?php echo $this->escapeHtml($module->getName()); ?>
                </a>
                <br>
                <strong>Author:</strong> <?php echo $this->escapeHtml($module->getOwner()) ?>
            </div>
        </div>
        <hr>
    <?php endforeach; ?>
</div>
