<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php $this->headTitle('ZF2 Modules')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php echo $this->headTitle(); ?>

        <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
        <?php $this->headMeta()->setCharset('UTF-8'); ?>
        <?php echo $this->headMeta(); ?>

        <?php $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . '/favicon.ico']); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css'); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/slide.css'); ?>
        <?php $this->headLink()->appendAlternate($this->url('feed'), 'application/rss+xml', 'RSS Feed for ZF2 Modules'); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <a href="https://github.com/zendframework/modules.zendframework.com"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"></a>

        <div id="toppanel">
            <div class="tab">
                <ul class="login">
                    <li class="left">&nbsp;</li>
                    <li><a href="<?php echo $this->url('home'); ?>">Home</a></li>
                    <?php $userDisplayName = $this->zfcUserDisplayName(); ?>
                    <?php if ($userDisplayName): ?>
                        <li class="sep">|</li>
                        <li class="user-info">
                            <?php /* @var User\Entity\User $identity */ ?>
                            <?php $identity = $this->zfcUserIdentity(); ?>
                            <div class="gravatar-container"><a class="login" href="<?php
                                echo $this->url('zfcuser');
                                ?>" title="My profile">
                                    <img src="<?php
                                    echo $this->escapeHtmlAttr($identity->getPhotoUrl());
                                    ?>" alt="<?php echo $this->escapeHtmlAttr($this->zfcUserDisplayName());
                                    ?>" style="width:23px;height:23px;" />
                                </a></div><a class="login" href="<?php echo $this->url('zfcuser') ?>" title="My profile"> Hello <?php echo $this->escapeHtml(ucfirst($userDisplayName)); ?></a>
                        </li>
                        <li class="sep">|</li>
                        <li ><a href="<?php echo $this->url('zfcuser/logout'); ?>">Logout</a></li>
                    <?php else: ?>
                        <li id="toggle">
                            <a class="login" href="<?php echo $this->url('scn-social-auth-user/login/provider', ['provider' => 'github']); ?>">GitHub Login</a>
                        </li>
                    <?php endif; ?>
                    <li class="right">&nbsp;</li>
                </ul>
            </div>
        </div>

        <div class="container-fluid landing-intro small-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <a href="<?php echo $this->url('home'); ?>" style="text-decoration:none">
                            <img src="<?php echo $this->basePath('/img/zend-logo_small.png'); ?>" alt="ZF Modules"/>
                            <p class="zf-green">Modules</p>
                        </a>
                    </div>
                    <div class="col-md-4">

                    </div>
                </div>
            </div>
        </div>


        <div class="container main-content">
            <div class="container-fluid">
                <?php echo $this->content; ?>
            </div
        </div>
        <hr style="clear:both" />

        <?php echo $this->partial('layout/footer'); ?>

        <?php $this->inlineScript()->prependFile($this->basePath() . '/js/bootstrap.min.js'); ?>
        <?php $this->inlineScript()->prependFile($this->basePath() . '/js/jquery-1.11.2.min.js'); ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
