<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <?php echo $this->headTitle('ZF2 Modules')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->setCharset('UTF-8')
    ?>

    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->appendStylesheet($this->basePath() . '/css/style.css')
            ->appendStylesheet($this->basePath() . '/css/slide.css')
    ?>
</head>
<body>
<a href="https://github.com/zendframework/modules.zendframework.com"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"></a>

<div id="toppanel">
    <!-- /login -->
    <!-- The tab on top -->
    <div class="tab">
        <ul class="login">
            <li class="left">&nbsp;</li>
            <li ><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
            <?php
                $userDisplayName = $this->zfcUserDisplayName();
                if ($userDisplayName):
            ?>
            <li class="sep">|</li>
            <li class="user-info">
                <div class="gravatar-container"><a class="login" href="<?php
                    echo $this->url('zfcuser');
                ?>" title="My profile">
                <img src="<?php
                    echo $this->zfcUserIdentity()->getPhotoUrl();
                ?>" alt="<?php echo $this->zfcUserDisplayName();
                ?>" style="width:23px;height:23px;" />
                </a></div><a class="login" href="<?php
                    echo $this->url('zfcuser');
                ?>" title="My profile"> Hello <?=ucfirst($userDisplayName);?></a>
            </li>
            <li class="sep">|</li>
            <li ><a href="user/logout">Logout</a></li>
            <?php else: ?>
            <li id="toggle">
            <a class="login" href="<?php
                echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'github'));
            ?>">GitHub Login</a>
            </li>
            <?php endif; ?>
            <li class="right">&nbsp;</li>
        </ul>
    </div> <!-- / top -->
</div>

<div class="container-fluid landing-intro small-header">
    <div class="container">
        <div class="row">
            <div class="span8">
                <a href="/" style="text-decoration:none">
                    <img src="/img/zend-logo_small.png" alt="ZF Modules"/>
                    <p class="zf-green">Modules</p>
                </a>
            </div>
            <div class="span4">

            </div>
        </div>
    </div>
</div>


<div class="container main-content">
    <?php echo $this->content; ?>
</div>
<hr style="clear:both" />

<footer class="footer">
    <div class="container">
        <p><?=COPY_MSG;?></p>
    </div>
</footer>

<?php echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
//                ->appendFile($this->basePath() . '/js/slide.js')
        ?>
</body>
</html>
