<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <?php echo $this->headTitle('ZF2 Modules')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->appendStylesheet($this->basePath() . '/css/style.css') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">Modules</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript()->appendFile($this->basePath() . '/js/bootstrap.min.js') ?>
  </body>
</html>
