<h1>Welcome to the ZF2 Modules Site</h1>

<article class="triple">
    <header>What is this site</header>
    <div>
        <p>This is a community generated site where you can find and share modules that have been created Using Zend Framework 2</p>
        <p>We hope to act as a central location for browsing, searching and reviewing ZF Modules.</p>
        <p><strong>If you are interested in submitting a module for inclusion into the site you can contact us on the #zftalk.2 channel on freenode to find out how. (at least till we think of a better way)</strong></p>
    </div>
</article>

<article class="triple last">
    <header><a id="help">We need help - Be a volunteer</a></header>
    <div>
        <p>We are actively recruiting volunteers to help build this community site.</p>
        <p>If you are interested in helping with this project, simply fork the code on <a href="https://github.com/zendframework/modules.zendframework.com">GitHub</a> and get started!.</p>
        <p><strong>Additionally, join us in #zftalk.2 on Freenode and ask how you can help!</strong></p>
    </div>
</article>

<article class="wide">
    <header><a id="modules">Modules</a></header>
    <div>
        <p>The new ZF2 module system is very young; and as such, there are not many modules yet.</p>
        <p>Below are some links to modules under development. Remember, ZF2 and the module system is beta and not meant to be used in production. These modules are not tested, reveiwed by anyone, or guaranteed to work at all.</p>
        <ul>
            <li><a href="https://github.com/widmogrod/zf2-assetic-module">AsseticBundle</a> -  Privides asset managment (depended of route-name, controller-alias-name [di]). Core of module is <a href="https://github.com/kriswallsmith/assetic">Assetic</a> library. By <a href="https://github.com/widmogrod">Gabriel Habryn</a>.</li>
            <li><a href="https://github.com/DASPRiD/AssetLoader">AssetLoader</a> – Provides loading of assets within modules. By <a href="http://www.dasprids.de">Ben Scholzen</a></li>
            <li><a href="https://github.com/DASPRiD/Bacon">Bacon</a> - Provides a unidecoder/slugifier, as well a as a PHP port of 'highlight'. By <a href="http://www.dasprids.de/">Ben Scholzen</a>.</li>
            <li><a href="https://github.com/bjyoungblood/BjyAuthorize">BjyAuthorize</a> - Provides an identity-aware wrapper for Zend\Acl compatible with ZfcUser. By <a href="http://bjyoungblood.com">Ben Youngblood</a>.</li>
            <li><a href="https://github.com/bjyoungblood/BjyCacheStorage">BjyCacheStorage</a> - Provides various (currently only Redis) cache storage adapters for Zend\Cache. By <a href="http://bjyoungblood.com">Ben Youngblood</a>.</li>
            <li><a href="https://github.com/bjyoungblood/BjyProfiler">BjyProfiler</a> - Zend\Db query profiler (also a plugin for ZendDeveloperTools). By <a href="http://bjyoungblood.com">Ben Youngblood</a>.</li>
            <li>
                <a href="https://github.com/doctrine/DoctrineModule">DoctrineModule</a> - Complete Doctrine 2.x integration for your ZF2 application with pagination, validators, and auth adapters.
                <ul>
                    <li><a href="https://github.com/doctrine/DoctrineORMModule">DoctrineORMModule</a> - DoctrineORM provider for DoctrineModule.</li>
                    <li><a href="https://github.com/doctrine/DoctrineMongoODMModule">DoctrineMongoODMModule</a> - MongoODM provider for DoctrineModule.</li>
                </ul>
            </li>
            <li><a href="https://github.com/superdweebie/DojoModule">DojoModule</a> A simple module to integrate Dojo 1.7 with zf2. Includes basic structure for view helpers, and a skeleton for bootstrapping dojo. By Tim Roediger.</li>
            <li><a href="https://github.com/EvanDotPro/EdpMarkdown">EdpMarkdown</a> - Uses the <a href="http://michelf.com/projects/php-markdown/">PHP Markdown</a> parser to provide a very simple markdown view helper. By <a href="http://blog.evan.pro/">Evan Coury</a>.</li>
            <li><a href="https://github.com/EvanDotPro/EdpSuperluminal">EdpSuperluminal</a> - Caches the common Zend\* classes used by your application into a single cache file, reducing reliance on the autoloader, and greatly improving the baseline performance of ZF2. By <a href="http://blog.evan.pro/">Evan Coury</a>.</li>
            <li><a href="https://github.com/Ocramius/OcraDiCompiler">OcraDiCompiler</a> - Compiles the default Zend\Di instance into a very fast dependency injection container proxy, making your application blazing fast. By <a href="http://marco-pivetta.com/">Marco Pivetta</a>.</li>
            <li><a href="https://github.com/widmogrod/zf2-facebook-module">FacebookBundle</a> -  Privides very simple integration with <a href="https://github.com/facebook/php-sdk">Facebook php-sdk</a> library. By <a href="https://github.com/widmogrod">Gabriel Habryn</a>.</li>
            <li><a href="https://github.com/artur-gajewski/FileBank">FileBank</a> -  Provides simple way to save files and their metadata into database and retrieve them with a view hel$
            <li><a href="https://github.com/artur-gajewski/GoogleWeather">GoogleWeather</a> -  Provides access to Google's weather forecast. Current weather and forecast for given city $
            <li><a href="https://github.com/basz/zf2-module-ideal-service">iDealService</a> - Module for the online payment system <a href="http://http://www.ideal.nl/?s=&lang=eng-GB">iDeal</a> which to free shop owners from specific acquirers 'lock-in'. It does this by having a unified interface on top of vendor specific adapters. By <a href="http://www.bushbaby.nl/">Bas Kamer</a>.</li>
            <li><a href="https://github.com/mistmodules/MistDoctrine">MistDoctrine</a> - Provides a somewhat bare bones Doctrine 2.x integration. By <a href="http://www.michielstaessen.be/">Michiel Staessen</a>.</li>
            <li><a href="https://github.com/mwillbanks/mwGearman">mwGearman</a> - Provides a module for <a href="http://gearman.org">Gearman</a> integration.  Currently only supports PECL Gearman. By <a href="http://blog.digitalstruct.com">Mike Willbanks</a></li>
            <li><a href="https://github.com/EvanDotPro/MwopGuestbook">MwopGuestbook</a> - Provides very simple Guestbook functionality. Built as a demo for the zf-quickstart. By <a href="http://weierophinney.net/matthew/">Matthew Weier O'Phinney</a>.</li>
            <li><a href="https://github.com/ocramius/OcraComposer">OcraComposer</a> - Provides composer autoloading for modules, helps in composer setup. By <a href="http://marco-pivetta.com/">Marco Pivetta</a>.</li>
            <li><a href="http://git.mwop.net/?a=summary&p=PhlyBlog">PhlyBlog</a> - Provides a static blog generator. By <a href="http://mwop.net/">Matthew Weier O'Phinney</a></li>
            <li><a href="http://git.mwop.net/?a=summary&p=PhlyCommon">PhlyCommon</a> - Provides SPL extensions and generic interfaces for entities and collections. By <a href="http://mwop.net/">Matthew Weier O'Phinney</a></li>
            <li><a href="http://git.mwop.net/?a=summary&p=PhlyContact">PhlyContact</a> - Provides a CAPTCHA-protected contact form, with the ability to configure the mail transport. By <a href="http://mwop.net/">Matthew Weier O'Phinney</a></li>
            <li><a href="https://github.com/silvester/ReverseUniForm">ReverseUniForm Module</a> - Implements Zend from decorators to use with Uni-Form css framework and adds some new elements. By <a href="http://maraz.org/">Silvester Maraž</a>.</li>
            <li><a href="http://git.mwop.net/?a=summary&p=SkeletonCss">SkeletonCss</a> - Provides <a href="http://getskeleton.com/">Skeleton CSS</a> assets. Packaged by <a href="http://mwop.net/">Matthew Weier O'Phinney</a></li>
            <li><a href="https://github.com/widmogrod/zf2-twitter-bootstrap-module">TwitterBootstrap</a> -  Provides Zend_Form integration with <a href="https://github.com/twitter/bootstrap">twitter bootstrap toolkit</a>. By <a href="https://github.com/widmogrod">Gabriel Habryn</a>.</li>
            <li><a href="https://github.com/zendframework/ZendDeveloperTools">ZendDeveloperTools</a> - Will eventually provide a JS/CSS floating toolbar with helpful debugging tools such as profiling and debugging output.</li>
            <li><a href="https://github.com/zendframework/ZendSkeletonModule">ZendSkeletonModule</a> - Provides a simple starting place for developing typical MVC-oriented modules.</li>
            <li><a href="https://github.com/Ocramius/ZfPhpcrOdm">ZfPhpcrOdm</a> - Provides integration of Doctrine PHPCR ODM for ZF2 applications through Doctrine DBAL/Jackrabbit or Midgard 2. By <a href="http://marco-pivetta.com/">Marco Pivetta</a>.</li>
            <li><a href="https://github.com/mwillbanks/ZfcTwitterBootstrap">ZfcTwitterBootstrap</a> - Provides Twitter Bootstrap integration.  (Currently unofficial -- pending ZF-Commons vote).</li>)
            <li><a href="https://github.com/Zf-Commons/ZfcUser">ZfcUser (Formerly EdpUser)</a> - Provides a very simple and customizable user authentication and registration system. The goal is to support Zend\Db out of the box and Doctrine2.x ORM and MongoDB ODM via adapter modules. By <a href="https://zf-commons.github.com/">ZF-Commons Team</a>.
                <ul>
                    <li>Official Extensions
                        <ul>
                            <li><a href="https://github.com/ZF-Commons/ZfcUserDoctrineORM">ZfcUserDoctrineORM</a> - Enables ZfcUser to utilize Doctrine 2.x ORM (requires the official <a href="https://github.com/doctrine/DoctrineModule">DoctrineModule</a> and <a href="https://github.com/doctrine/DoctrineORMModule">DoctrineORMModule</a> modules.</li>
                            <li><a href="https://github.com/ZF-Commons/ZfcUserDoctrineMongoODM">ZfcUserDoctrineMongoODM</a> - Enables ZfcUser to utilize Doctrine 2.x MongoDB ODM (requires the official <a href="https://github.com/doctrine/DoctrineModule">DoctrineModule</a> and <a href="https://github.com/doctrine/DoctrineMongoODMModule">DoctrineMongoODMModule</a> modules.</li>
                        </ul>
                    </li>
                    <li>3rd-Party Extensions
                        <ul>
                            <li><a href="https://github.com/cdli/CdliUserProfile">CdliUserProfile</a> - Extensible user-editable profile for ZfcUser. By <a href="https://github.com/adamlundrigan" target="_blank">Adam Lundrigan</a>/<a href="https://github.com/cdli" target="_blank">CDLI</a></li>
                            <li><a href="https://github.com/cdli/CdliTwoStageSignup">CdliTwoStageSignup</a> - Pre-registration email validation module for ZfcUser. By <a href="https://github.com/adamlundrigan" target="_blank">Adam Lundrigan</a>/<a href="https://github.com/cdli" target="_blank">CDLI</a></li>
                            <li><a href="https://github.com/cdli/CdliAutogenUsername">CdliAutogenUsername</a> - Autogenerated username plugin for ZfcUser. By <a href="https://github.com/adamlundrigan" target="_blank">Adam Lundrigan</a>/<a href="https://github.com/cdli" target="_blank">CDLI</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="https://github.com/mtymek/ZfTwig">ZfTwig</a> - Provides integration of <a href="http://twig.sensiolabs.org/">Twig templating engine</a>. By <a href="https://github.com/mtymek">Mateusz Tymek</a>.</li>
            <li><a href="https://github.com/basz/zf2-module-phing-service">PhingService</a> - Exposes <a href="http://www.phing.info">Phing</a> within ZF2, a PHP project build system or build tool based on Apache Ant. By <a href="http://www.bushbaby.nl/">Bas Kamer</a>.</li>
            <li><a href="https://github.com/juriansluiman/SlmMail">SlmMail</a> - Provides several api implementations of the largest Email Service Providers. Examples: Amazon SES, ElasticEmail, Mailchimp, Postage, Postmark, SendGrid. By <a href="http://juriansluiman.nl">Jurian Sluiman</a></li>
            <li><a href="https://github.com/juriansluiman/SlmGoogleAnalytics">SlmGoogleAnalytics</a> - Provides integration of Google Analytics page tracking, event tracking and ecommerce tracking. By <a href="http://juriansluiman.nl">Jurian Sluiman</a></li>
            <li><a href="https://github.com/juriansluiman/GedmoDoctrineExtensions">GedmoDoctrineExtensions</a> - Provides the Doctrine Extensions from "l3pp4rd", to be used with the DoctrineModule and DoctrineORMModule. By <a href="http://juriansluiman.nl">Jurian Sluiman</a></li>
            <li><a href="https://github.com/juriansluiman/ChromePhpLogger">ChromePhpLogger</a> - Provides the logging utility for Chrome, able to use with Zend\Log. By <a href="http://juriansluiman.nl">Jurian Sluiman</a></li>
            <li><a href="https://github.com/blanchonvincent/zf2-lazy-loading-module">ZFModuleLazyLoading</a> - Provides a lazy loading modules. By <a href="http://developpeur-zend-framework.fr/">Vincent Blanchon</a></li>
            <li><a href="https://github.com/blanchonvincent/ZF2-Parallel">ZFParallelJobs</a> - Provides a fork manager. By <a href="http://developpeur-zend-framework.fr/">Vincent Blanchon</a></li>
            <li><a href="https://github.com/ZendExperts/ZeTwig">ZeTwig</a> - Integrates <a href="http://twig.sensiolabs.org/">Twig templating engine</a> in ZF2 applications with additional extensions for rendering actions and triggering events from within your templates. By <a href="http://www.zendexperts.com">ZendExperts</a>.</li>
            <li><a href="https://github.com/ZendExperts/ZeSecurity">ZeSecurity</a> - Provides out of the box security layer currently using only IDS(Intrusion Detection System) based on PHPIDS. By <a href="http://www.zendexperts.com">ZendExperts</a>.</li>
            <li><a href="https://github.com/ZendExperts/ZeTheme">ZeTheme</a> - Allows you to switch between various themes (created by you or someone else). You can also define on what conditions a theme should be used. By <a href="http://www.zendexperts.com">ZendExperts</a>.</li>
        </ul>
    </div>
</article>
