<h1>Welcome to the ZF2 Modules Site</h1>

<article class="triple">
    <header>What is this site</header>
    <div>
        <p>This is a community generated site where you can find and share modules that have been created Using Zend Framework 2</p>
        <p>We hope to act as a central location for browsing, searching and reviewing ZF Modules.</p>
        <p><strong>If you are interested in submitting a module for inclusion into the site you can contact us on the #zftalk.2 channel on freenode to find out how. (at least till we think of a better way)</strong></p>
    </div>
</article>

<article class="triple last">
    <header><a id="help">We need help - Be a volunteer</a></header>
    <div>
        <p>We are actively recruiting volunteers to help build this community site.</p>
        <p>If you are interested in helping with this project, simply fork the code on <a href="https://github.com/zendframework/modules.zendframework.com">GitHub</a> and get started!.</p>
        <p><strong>Additionally, join us in #zftalk.2 on Freenode and ask how you can help!</strong></p>
    </div>
</article>

<article class="wide">
    <header><a id="modules">Modules</a></header>
    <div>
        <p>The new ZF2 module system is very young; and as such, there are not many modules yet.</p>
        <p>Below are some links to modules under development. Remember, ZF2 and the module system is beta and not meant to be used in production. These modules are not tested, reveiwed by anyone, or guaranteed to work at all.</p>
        <ul>
            <li><a href="https://github.com/zendframework/ZendSkeletonModule">ZendSkeletonModule</a> - Provides a simple starting place for developing typical MVC-oriented modules.</li>
            <li><a href="https://github.com/zendframework/ZendDeveloperTools">ZendDeveloperTools</a> - Will eventually provide a JS/CSS floating toolbar with helpful debugging tools such as profiling and debugging output.</li>
			<li><a href="https://github.com/mstaessen/zf2-doctrine-provider">DoctrineProvider</a> - Provides a very basic Doctrine 2.x integration. By <a href="http://www.michielstaessen.be/">Michiel Staessen</a>.</li>
            <li><a href="https://github.com/SpiffyJr/SpiffyDoctrine">SpiffyDoctrine</a> - Provides simple and complete integration of Doctrine 2.x for your ZF2 application. Also provides validators such as EntityExists and NoEntityExists (for use by components like Zend\Form) as well as a Zend\Authentication adapter. By <a href="http://www.spiffyjr.me/">Kyle Spraggs</a>.</li>
            <li><a href="https://github.com/Ocramius/ZfMongoDbOdm">ZfMongoDbOdm</a> - Provides a very simple integration of Doctrine MongoDB ODM 1.0.0RC1-DEV for ZF2 applications. By <a href="http://marco-pivetta.com/">Marco Pivetta</a>.</li>
            <li><a href="https://github.com/EvanDotPro/EdpUser">EdpUser</a> - Provides a very simple and customizable user authentication and registration system. The goal is to support Doctrine2.x (using SpiffyDoctrine) _AND_ Zend\Db out of the box. By <a href="http://blog.evan.pro/">Evan Coury</a>.</li>
            <li><a href="https://github.com/EvanDotPro/EdpMarkdown">EdpMarkdown</a> - Uses the <a href="http://michelf.com/projects/php-markdown/">PHP Markdown</a> parser to provide a very simple markdown view helper. By <a href="http://blog.evan.pro/">Evan Coury</a>.</li>
            <li><a href="https://github.com/DASPRiD/Bacon">Bacon</a> - Provides a unidecoder/slugifier, as well a as a PHP port of 'highlight'. By <a href="http://www.dasprids.de/">Ben Scholzen</a>.</li>
            <li><a href="https://github.com/EvanDotPro/MwopGuestbook">MwopGuestbook</a> - Provides very simple Guestbook functionality. Built as a demo for the zf-quickstart. By <a href="http://weierophinney.net/matthew/">Matthew Weier O'Phinney</a>.</li>
            <li><a href="https://github.com/silvester/ReverseUniForm">ReverseUniForm Module</a> - Implements Zend from decorators to use with Uni-Form css framework and adds some new elements. By <a href="http://maraz.org/">Silvester Maraž</a>.</li>
        </ul>
    </div>
</article>
