<h1 style="text-align:center">Sign in</h1>
<div class="well" style="text-align:center">
    <p>
        There is no sign-up form anymore! Just log in with your GitHub account. All your information will be provided by GitHub.
    </p>
    <?php foreach ($this->options->getEnabledProviders() as $provider): ?>
        <p><?php echo $this->socialSignInButton($provider); ?></p>
    <?php endforeach; ?>
</div>
