  
  <div class="hero-unit">
    <h1>Welcome to the ZF2 Modules Site</h1>
    <p>This website is a work-in-progress. In the future you will be able to use this website to browse, search, rate, and comment on all of the great modules the Zend Framework community has to offer.</p>
  </div>
  <div class="container">
    <div class="span6 well">
      <h2>Find Modules</h2>
      <h5>Currently <?=count($this->repositories)?> Module for Zend Framework 2</h5>
      <hr/>

      <?php foreach($this->repositories as $repo) { ?>
        <div style="float:left">
          <p><a href="<?=$repo->getUrl()?>"><?=$repo->getName()?></a></p>
          <p><?=$repo->getDescription()?></p>
          <p>owner: owner here license: license here </p>
          <hr />
        </div>
        <div style="background-color:#000;color:#fff;height:64px;width:64px;float:right">
          owner picture
        </div>
      <?php } ?>
    </div>
    <div class="span4 well">
      <div >
        new Modules here
      </div>
      <div >
        New Developers here
      </div>
    </div>
  </div>
 