<?php $this->headTitle(sprintf('Browse %d modules for Zend Framework 2', $this->totalModules())); ?>

<div class="row">
    <div class="span8">
      <div class="row-fluid">
        <div class="span12">
          <div class="navbar">
            <div class="navbar-inner" >
              <form class="navbar-search pull-left span12" id="live-search">
                <input type="text" name="query" class="search-query span12" placeholder="Type to start searching...">
              </form>
            </div>
            <?php
            $this->inlineScript()->appendScript('
                $(\'#live-search input[name="query"]\').liveSearch({url: "/live-search?query="});
            ');?>

          </div>
        </div>
      </div>
        <?php foreach($this->repositories as $module) { ?>
        <div class="row-fluid module-row">
            <div class="span12">
                <div class="row-fluid">
                    <div class="module-info">
                        <div class="span6 module-author">
                            <div class="row-fluid">
                                <div class="span3">
                                    <img src="<?php echo $module->getPhotoUrl()?>" alt="<?php echo $module->getOwner()?>" class="avatar">
                                </div>
                                <div class="span9">
                                    <strong><?php echo $module->getOwner()?></strong>
                                    <p>
                                        <span class="author-label">Github:</span>
                                        <a href="<?php echo $module->getUrl()?>"><?php echo $module->getName()?></a>
                                        <!--
                                  <span class="author-label">Blog:</span> <a>placeholder</a><br />
                                  <span class="author-label">Modules:</span> <a>5</a><br /><br />
                                  <span class="author-label"><a>More info...</a>-->
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <strong><a href="<?php
                                            echo
                                            $this->url('view-module', array(
                                                    'vendor' => $module->getOwner(),
                                                    'module' =>  $module->getName(),
                                                )
                                            );?>"><?php echo $module->getName()?></a></strong>
                            <p>
                                <!--<span class="author-label">Version:</span> 1.2.1<br />-->
                                 <span class="author-label">Created:</span> <?php
                                                            $date = new DateTime($module->getCreatedAt());
                                                            echo $date->format('Y-m-d');
                                                            ?><br>
                                <!--<span class="author-label">Edited:</span> <a>15 days ago</a><br />
                            <span class="author-label">Tags:</span>
                            <span class="label">zf2</span>
                            <span class="label">Assetic</span>
                            <span class="label">Assets</span>
                            <span class="label">Sx</span>-->
                            </p>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="module-description">
                        <div class="span12">
                            <p>
                                <?php echo $module->getDescription()?>
                            </p>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>
            </div>
        </div><?php } ?>
        <?php echo $this->paginationControl($this->repositories, 'Sliding', 'application/index/pagination', array('query' =>$query)); ?>
    </div>
    <div class="span4">
        <div class="sidebar">
            <?php echo $this->newModule() ?>
            <?php echo $this->newUsers() ?>
        </div>
    </div>
</div>
