<?php if ($this->pageCount): ?>
    <div class="row">
        <div class="col-xs-12 pull-right">
            <div class="pull-right">
                <ul class="pagination">
                    <?php if (isset($this->previous)): ?>
                        <li>
                            <a href="<?php echo $this->url('home', [], ['query' => ['query' => $this->query, 'page' => $this->first]]); ?>">&lt;&lt; First</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('home', [], ['query' => ['query' => $this->$query, 'page' => $this->previous]]); ?>">&lt; Previous</a>
                        </li>
                    <?php endif; ?>
                    <?php foreach ($this->pagesInRange as $page): ?>
                        <li<?php echo ($page == $this->current) ? ' class="active"' : '' ?>>
                            <a href="<?php echo $this->url('home', [], ['query' => ['query' => $this->query, 'page' => $page]]); ?>"><?php echo $page; ?></a>
                        </li>
                    <?php endforeach; ?>
                    <?php if (isset($this->next)): ?>
                        <li>
                            <a href="<?php echo $this->url('home', [], ['query' => ['query' => $this->query, 'page' => $this->next]]); ?>">Next &gt;</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('home', [], ['query' => ['query' => $this->query, 'page' => $this->last]]); ?>">Last &gt;&gt;</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
