<?php if ($this->pageCount): ?>
    <div class="row-fluid module-row">
        <div class="span12">
            <div class="row-fluid">
                <div class="pagination pull-right">
                    <ul>
                        <?php if (isset($this->previous)): ?>
                            <li>
                                <a href="<?php echo $this->url('home', ['page' => $this->first], ['query' => ['query' => $query]]); ?>">&lt;&lt; First</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('home', ['page' => $this->previous], ['query' => ['query' => $query]]); ?>">Previous &gt;</a>
                            </li>
                        <?php endif; ?>
                        <?php foreach ($this->pagesInRange as $page): ?>
                            <li<?php echo ($page == $this->current) ? ' class="active"' : '' ?>>
                                <a href="<?php echo $this->url('home', ['page' => $page], ['query' => ['query' => $query]]); ?>"><?php echo $page; ?></a>
                            </li>
                        <?php endforeach; ?>
                        <?php if (isset($this->next)): ?>
                            <li>
                                <a href="<?php echo $this->url('home', ['page' => $this->next], ['query' => ['query' => $query]]); ?>">Next &gt;</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('home', ['page' => $this->last], ['query' => ['query' => $query]]); ?>">Last &gt;&gt;</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
